repos:
  - repo: local
    hooks:
      - id: shellcheck
        name: shellcheck
        entry: shellcheck
        language: system
        types: [shell]
        exclude: \.tmpl$
      - id: shellcheck-templates
        name: shellcheck (templates)
        entry: sh -c 'rc=0; for f; do chezmoi execute-template < "$f" | shellcheck -s bash - || { echo "^ $f"; rc=1; }; done; exit $rc' --
        language: system
        files: ^run_.*\.sh\.tmpl$
